

plugins = []
headers = []
redirects = []

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]

[functions."*"]

[build]
publish = "dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "ENDPOINT_URL_S3,REGION,STORAGE_BUCKET_NAME"
  SECRETS_SCAN_OMIT_PATHS = "utils/audioHelpers.ts,src/db/queries.ts,src/lib/s3.ts"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]