[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["vite"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/api/uploads/:splat"
  status = 200

[[redirects]]
  from = "/Audio/*"
  to = "/.netlify/functions/api/Audio/:splat"
  status = 200

[[redirects]]
  from = "/samples/*"
  to = "/.netlify/functions/api/samples/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
